### ISSUE TITLE
Never ending loop when trying to compare 2 version strings

### ISSUE THREAD

**Issue by machxli** [fsaintjacques/semver-tool#14]
Hi fsaintjacques.

At first, I want to thank You for such a great utility.

Despite the fact, that You primary targeted this tool for project usage, it also have possibility to compare 2 strings (which is my case):

> semver compare \<ver1> \<ver2>

In case of compare two version strings, it ends in never ending loop when trying to find version file, since I'm running semver as utility (no .version file anywhere).
Maybe you should consider to load vesion file in case if only 1 parameter is passed ([here](https://github.com/fsaintjacques/semver-tool/blob/develop/src/semver#L218)) instead of doing that for each case ([here](https://github.com/fsaintjacques/semver-tool/blob/develop/src/semver#L214)).

Thanks in advance

**Comment by fsaintjacques** [comment]
That is actually a bug. I'll fix it.

**Comment by fsaintjacques** [comment]
release 1.2.1 fixes this.

**Comment by fsaintjacques** [comment]
And release 2.0.0 completely review the way `semver` works :)
