### ISSUE TITLE
manipulate prerel numbered versions?

### ISSUE THREAD

**Issue by chadlavi-casebook** [fsaintjacques/semver-tool#25]
it would be great if this tool could bump the number of a prerel, for example something like 

```bash
$ semver bump prerel alpha 1.2.3-alpha.3
1.2.3-alpha.4
```

Currently bumping a prerel strips any numbered versioning that prerelease version has.

**Comment by fsaintjacques** [comment]
Feel free to provide a patch, but this is not a priority for me.
