### ISSUE TITLE
Merge semver-tool and git-semver?

### ISSUE THREAD

**Issue by markchalloner** [fsaintjacques/semver-tool#3]
Hi fsaintjacques

Independently of your tool (I only just found it now!) I built a git plugin for semantic versioning:

https://github.com/markchalloner/git-semver

This also has it's own plugin architecture that can be used for validating versions scattered around projects (e.g. change log, manifests etc), as well as a built in updater.

As the two project seem pretty complimentary, I was wondering if you would be interested in merging the two in a new independent organisation account and working together on it?

Thanks

**Comment by fsaintjacques** [comment]
Hey Mark,

I took a look at git-semver expose and there's small issues I have with:

* I created this project in order to couple it with *gitflow* which is responsible to create tag. The *semver* tool is only used to manipulate (bump|print) version files, e.g. you would use it as follow
```
# git flow release start $(semver bump --pretend minor)
# semver bump minor
# git commit -m "bumps to $(semver)"
# git flow release finish $(semver)

...

# git flow bugfix start $(semver bump --pretend patch)
# fix stuff
# semver bump patch
# git commit -m "bumps to $(semver)"
# git flow bugfix finish $(semver)
```
* The update/uninstall feature should not be embedded in the program itself. Let the packagers and admins handle maintenance.
* The `usage`  definition and the call syntax does not match, e.g. 
```
git semver [major|minor|patch|next]
# git semver patch|next
```
* It seems to be missing `prerel` and/or `build` support.

I believe that the first point is a blocker to both philosophy of the project. We could tweak git-semver to optionally support tag manipulation. On the other side, I love that it supports multiple version storage (changelog, package.json).

**Comment by fsaintjacques** [comment]
Also note that this project is 100% decoupled from git, so I'd still want to have that property, i.e. make a standalone semver bash utils (like this) and then make a git-semver plugin that reuse the functionnality.

**Comment by markchalloner** [comment]
Cheers for the feedback François. Numbering for reference:

1. Regarding philosophy of the projects. In my opinion writing a git tag (or hg/svn tag for that matter) is only one possible output of versioning, others could be writing to a .version file (as semver-tool does) another manifest file, just printing on the terminal (semver --pretend) or even sending to a remote server (a bit "out there" and not sure of the use case but its all possible).
2. I've been considering moving from the passive plugin architecture git-semver currently has (just validating version files) to a more active one (updating version files). Git tagging would then naturally become a plugin.
3. Regarding decoupling from git, agreed. I think plugging into other systems should be an optional feature, not a dependency, and would make sense anyway in the event of point 2.

Cheers

**Comment by fsaintjacques** [comment]
See the fsaintjacques@semver-tools:feature/modular-backend for an initial implementation. The first drawback is that `semver` is not a contained script anymore and needs to be installed with `make`. This could be hacked if we inject the module code in the script itself.

**Comment by josefsalyer** [comment]
I believe that there should be a command line utility to handle semantic versioning that is decoupled from anyone's VCS.

@fsaintjacques - I'm interested in contributing to this project.  Let me know if you have a feature / issue board somewhere that I can pull from.

**Comment by fsaintjacques** [comment]
@josefsalyer the module-backend allows the init command to install a module that defines how to read/write the version. For example, the existing behaviour (found in develop branch) is storing the version in a file called .version in the root directory of your project. Other possible module:

- file: .version
- node: package.json
- git: git tags
- maven: pom.xml
