### ISSUE TITLE
Piping doesn't work

### ISSUE THREAD

**Issue by mindfullsilence** [fsaintjacques/semver-tool#31]
Maybe I'm doing something wrong, but seems as though this should work:

```
git tag --sort=v:refname | tail -n 1 | semver get major
```

Instead it errors and gives the usage guide

**Comment by fsaintjacques** [comment]
`semver get (part) <version>` doesn't read from stdin but expects an argument. Try with `git tag --sort=v:refname | tail -n 1 | xargs -L1 semver get major`.

**Comment by mindfullsilence** [comment]
Noice, forgot all about xargs somehow.
