### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by WoLfulus** [fsaintjacques/semver-tool#32]
I see this is licensed as GPLv3, is there a reason for being that restrictive?

I'm bundling the script into a project of mine which I was planning on releasing as MIT and I've read that they are not compatible. I'm not planning on making my project GPLv3, how should I proceed?

I'm not making any changes to the script, I'm just bundling it to avoid having to manually install it inside a docker container.

Thanks :)

**Comment by WoLfulus** [comment]
@fsaintjacques would you mind commenting on this, please? :)

**Comment by fsaintjacques** [comment]
Considering a lot of people contributed patch to this project, I don't think this is [feasible](https://softwareengineering.stackexchange.com/questions/55326/can-you-change-a-license-once-you-pick-one).

**Comment by WoLfulus** [comment]
I wonder how I'd be able to contact them. Maybe I should @ping each one of them in this issue to get their approval?

**Comment by WoLfulus** [comment]
Also, before trying to contact the contributors, would you mind telling which license you'll be willing to change to? So that contributors know which one it will become? Is MIT fine for you?

Thanks!

**Comment by fsaintjacques** [comment]
MIT is fine for a tool like this one.

**Comment by WoLfulus** [comment]
This might be hard and take a while, but let's see...

@qyanu @particleflux @eviweb @bradfordboyle @kenjones-cisco @issaharw @alyssais @ah-clem @troian @ranger6 @mrzasa @llonchj @haguenau @azuenko 

What you all think? :)

**Comment by issaharw** [comment]
Fine by me

**Comment by ranger6** [comment]
I'd be fine with the MIT license.
The current license (GPL) as it would apply to most uses of this tool is not really that burdensome in terms of capturing other IP (copyleft).  Running a GPL app/script in the context of other software does not "taint" that software.  Lawyers sometimes get touchy about re-distributing GPL software along with other code (on the same disk, ...).
So, just to keep everyone calm, a more permissive license (e.g. MIT) seems fine.

**Comment by ah-clem** [comment]
MIT fine with me.

**Comment by alyssais** [comment]
@WoLfulus if you're only bundling the tool, then I think the GPL is
quite clear that you would not have GPL requirements imposed on the
other software.  See here for GNU's position, which sounds entirely
compatible with what you want to do:
https://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation

I don't think this license change is a good idea because I don't think
it's necessary for @WoLfulus's use case.  I don't see how the GPL would
apply to any software that wasn't an extension of this program, using
its internal functions, etc.

Now, my contributions to this program are minimal, and I doubt they
could be considered copyrightable, and for that reason, and to avoid
getting in the way if you want to be overcautious, I give my consent to
the relicensing.  Nevertheless, I recommend to the people who do hold
substantial copyright in the software that they resist weakening the
license for no good reason.

**Comment by WoLfulus** [comment]
I'll take a look at that @alyssais ! Thanks for the info :)

**Comment by azuenko** [comment]
no objections for moving to MIT

**Comment by troian** [comment]
No objections. MIT is a good one!

**Comment by bradfordboyle** [comment]
No objection to re-licensing under MIT.

**Comment by fsaintjacques** [comment]
ping @qyanu @eviweb @mrzasa @llonchj

**Comment by qyanu** [comment]
@WoLfulus @fsaintjacques 
My interpretation of european law (where i am seated) is, that my changes/commit do not meat the required threashold to constitute a protected work.
However, in the event that an authoritative entity has a different opinion, i already state in advance and irrevocably: i don't object to any use or any relicensing, including re-licensing under MIT.

**Comment by asad-awadia** [comment]
@fsaintjacques are we there yet?

**Comment by asad-awadia** [comment]
@eviweb @mrzasa @llonchj

**Comment by eviweb** [comment]
Hi, no objection for me.

**Comment by vsetka** [comment]
Of the remaining people to approve re-licensing, there's only one commit with changes to the actual code -> https://github.com/fsaintjacques/semver-tool/commit/1aabc20cbc574de0da24f62f2ac60d6d0ed0ac8a
All others are documentation changes. Can we re-license now or is commit by @llonchj considered copyrightable (I wouldn't think so)?

**Comment by ranger6** [comment]
An interesting point: the code changed in the below mentioned commit no longer exists; not just the changes, but the entire
function is gone; the referenced objects are gone; the design has changed; the logic has changed.  This was seven years ago,
and so, long before I even became aware of the project.  Perhaps this commit provoked other changes and so is really part
of the licensed code base is some way?  Perhaps it was a dead end “fork in the road”?  I wouldn’t know.

But it does seem a shame that a license change that could help others benefit from this code is held up for three lines of 7 year old dead and gone code.

Here is a thought experiment:

>What if the project were to fork just prior to the @llonchj commit and the new project changed the license.  Then the other contributors agreed that
a pull request with changes (based on their contributions) to bring the project up to date was then accepted.  I mean, it would be sort of
strange if a commit by one person could somehow poison all subsequent work by others.

Ha! Only kidding!  Best path forward is more reach-out to @llonchj

**Comment by ranger6** [comment]
FYI.  To keep conversations public, here is a copy of the note I sent to @llonchj (since he may not be receiving notifications from this project):
>Hello,
>
>In 2014, your contribution to the semver-tool was merged into the project: https://github.com/fsaintjacques/semver-tool/pull/2
>
>Today, there is a proposal to change this project’s license from "GNU Version 3” to “MIT”.  The motivation is that it makes sense for many to bundle this modest tool with other software without risking “poisoning” the other software.  The proposal has been opened as an issue on this project: https://github.com/fsaintjacques/semver-tool/issues/32.
>
>The project maintainer and copyright holder, François Saint-Jacques, believes that to change the license, we need to get the agreement of *all* the contributors.  You are the only remaining contributor (that is no longer active) that has not expressed an opinion. Everyone else agrees that changing the license is a good thing.
>
>Please take a look at the issue and leave a comment .. hopefully expressing your agreement.
>
>thanks for your time,
>— robert
>https://github.com/ranger6
>
>P.S. In case you are wondering, I tracked down your email address from the git commit log of your contribution.

**Comment by llonchj** [comment]
sorry for the late reply.
no objection to the license change

**Comment by fsaintjacques** [comment]
So it seems we can re-license .

**Comment by ranger6** [comment]
@fsaintjacques While you mention that "*we* can re-license", I think you should do the honors!  While you're "on-site", maybe you can accept my pull request #56 (no version number change).  Thanks!

**Comment by ranger6** [comment]
When changing the license, the badge in the `README.md` file needs to be fixed: it needs to point to the LICENSE file on the master branch.  It is currently broken, pointing to the `LICENSE` file on the "develop" branch.
