### ISSUE TITLE
Feature request: Add "validate" command

### ISSUE THREAD

**Issue by KreativeKrise** [fsaintjacques/semver-tool#38]
For a script I'm currently writing it would be nice to have an option to just validate a version string. Would it be possible to add something like `semver validate 0.1.0-dev+001`? And as a result it could return `version 0.1.0-dev+001 does match the semver scheme`. That would be really nice :)

**Comment by WoLfulus** [comment]
You could just check for the return code with $?, if it's zero then it's in a valid form.

Give it a try

**Comment by KreativeKrise** [comment]
@WoLfulus that was a nice idea! Thank you 🙏
