### ISSUE TITLE
Portability: Function names containing hyphens

### ISSUE THREAD

**Issue by Wonno** [fsaintjacques/semver-tool#41]
In order to improve compatibility with shells function identifiers may not contain a hyphens '-'

```
The following shells are known not to support hyphens in function names:

* ash (busybox), csh, tcsh, dash
```
Source: https://unix.stackexchange.com/a/168222

**Proposal:**
`function usage-version { `  -->  `function usage_version {`

**Comment by fsaintjacques** [comment]
I have no objection, feel free to submit a PR.

**Comment by Wonno** [comment]
Raised #42
