### ISSUE TITLE
Inconsistent re-naming of "is-nat"

### ISSUE THREAD

**Issue by ranger6** [fsaintjacques/semver-tool#44]
It looks like in commit e0a836c, "is-nat" was renamed to "is:_nat" in src/semver.  There is no mention of this (strange) naming in the commit log which was meant to resolve issue #42.  Looks like a typo in a global substitution to me.

Fix: replace "is:_nat" with "is_nat" everywhere.

**Comment by Wonno** [comment]
@ranger6  you are right.
