### ISSUE TITLE
"bats" test files are fragmented and inconsistent

### ISSUE THREAD

**Issue by ranger6** [fsaintjacques/semver-tool#52]
Currently, there are three "bats" unit test files.  There does not seem to be a motivation (why 3?), a naming convention, or consistency (different files test different things .. but then they sometimes overlap).
A clean-up is needed.  Suggestion: a single file, with tests organised by type/functionality (simple and just fine for a simple tool); or factor this out into separate files (can do this later if there is really a need).

**Comment by ferrgo** [comment]
Any guidelines on contributing?

**Comment by ranger6** [comment]
Hello,

Thanks for the interest.

This is a small project that moves forward at a leisurely pace without the need for a heavyweight process.  I’ve made a few contributions over the last couple years.  The repo owner brought me in as a collaborator.

We should really write a note on contributions.  Here is what I’ve observed as well as what I’d expect.  That is, my two cents:

1.  Content-wise: keep the project simple (a single purpose tool); new features need to have a real use case (not “nice to have”); compatibility and compliance are important.
2.  Code-wise: keep consistent naming and formatting and style.
3.  Commit-wise: submit a clean (squashed), documented pull-request that can be rebased on master. The content of the PR should be in the git commit log; rationale should be in the issue discussion thread.
4.  Assigning a semantic version string to this code and making clean releases needs work.  I’m sorta working on this.  Contributions should not be confused with releases.

As for issue #52.  I introduced the bats tests some time ago.  Over a couple iterations they have become fragmented and inconsistent.  Resolving this issue means looking at the tests, proposing an organisation and naming scheme (e.g. single file with sections, separate files by function/test type, ??).  Then the tests can be refactored and cleaned up.  Just to keep things
under control, I would not start adding/fixing/removing tests along the way: just create an issue(s) and attack that later.

Go for it!
— ranger6

**Comment by ferrgo** [comment]
Nice @ranger6 ! 

Thanks for those two cents, real nice and valuable. Going to keep that in mind, the bats refactoring seems a good way to get to know the project.

As for the item 4... I actually found this project searching for ways to easily keep a semver bumping on a project:
https://threedots.tech/post/automatic-semantic-versioning-in-gitlab-ci/ (pretty sure something like that would also be possible on github-workflows)

I'm currently reasearching a proper way to keep that in a git project, either by reading a commit, or infering this on branch naming on PR, etc... As of now I'm inclined to git-hooks as a way to do so, but not really sure. Would really apreaciate the options and look forward to what you're working on and your ideas on that matter.

**Comment by ranger6** [comment]
PR #64 closes this issue.
