### ISSUE TITLE
Wrong result when comparing pre-release and normal version

### ISSUE THREAD

**Issue by eviweb** [fsaintjacques/semver-tool#6]
Hi François,
as indicated in paragraph _11._ of the semver specification v2.0.0:
 _When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version_, which means  `1.0.0-alpha < 1.0.0`
so running `$ semver compare 1.0.0 1.0.0-alpha` should result in `1` when it currently returns `-1`
best regards
Eric

**Comment by LaurentGoderre** [comment]
I think there is a regression for this. version 2.1.0 has the same behavior. When running `semver compare 1.8.1 1.8.1-rc2` it should return 1 but returns -1
