### ISSUE TITLE
Request regarding "semver bump prerel"

### ISSUE THREAD

**Issue by conradreisch** [fsaintjacques/semver-tool#63]
Dear dev team,

I'm currently automating my build pipeline to apply semantic versioning. In the frontend app this is already working fine done with [npm version](https://docs.npmjs.com/cli/v6/commands/npm-version).
Whenever I have a "feature" oder "bugfix" branch, the pipeline is calling "npm verion prerelease --preid=dev". The first "prelease" call is adding the prerelease but also bumping the patch version. So I can always call this function:
- 0.1.0 --> 0.1.**1**-dev.1
- 0.1.1-dev.1 --> 0.1.1-dev.2

Merging back to master then calls a patch bump ("npm version patch" from 0.1.1-dev.2 to 0.1.1).
As you can see, the patch bump is not increasing the patch but just removing the prerelease part.

semver bump works a little bit different:
- semver bump prerel dev.. 0.1.0 --> 0.1.0-dev.1
- semver bump prerel dev.. 0.1.0-dev.1 --> 0.1.0-dev.2
- semver bump patch 0.1.0-dev.1 --> 0.1.1

My intuitive understanding is that npm patch bump works correctly. You want to switch from 1.0.0-rc.1 to 1.0.0

**Now my question: Is there any option to make semver work the same way?**
1. Increaing the patch version in a prerelease bump in case there is no prerelease part yet
2. Not increasing the patch version in a patch bump in case there is a prerelease part

**Comment by ranger6** [comment]
Thanks for the great request!  Always good to see real use cases.  Here is my first take (might need more thought):

1.  To your questions: no, there is not an option as you suggested.
2.  You are correct that, for example, `0.1.0-dev.1` precedes `0.1.0`.  So, using `semver` to "bump" the pre-release of a released version is abnormal.
3. The catch is that prior to adding a pre-release suffix, the development organisation needs to decide what the next target (release, or potential release) version will be.  It might be a patch release, it might be minor, or major.  To complicate things, there may be several target versions ongoing at any point in time.  The tool (any tool?) can't figure this all out.
4. In a CI/CD pipeline, someone has to trigger this.  Maybe it is a specific version, or perhaps it is something like "next patch", "next major".
5. `semver` does not work on stored instances, unlike some other tools.  It is a function: `command line -> stdout`.  So, one is free to provide whatever base version one wants to the `bump prerel` command.  Including:
```
% semver bump prerel dev.. $(semver bump patch 0.1.0)
```
A couple more comments for now:

First, every development and CI/CD organisation is different.  However, I find that semantic versioning can get in the way during the development process: too many things are in flux.  E.g. many bug fixes might be bundled into a single patch release.  One stream may well overtake another and you don't really want to release with version numbers out of order.

Second, it helps in automation if you can cut down on special cases.  That's one reason that you can use the `bump prerel` unchanged from first use to last (i.e. from adding the prefix through incrementing it): the command line does not change. Now, the command line given above _does not respect this_.  I would be interested in any ideas of how to clean that up (if indeed, it really needs cleaning up!).

**Comment by conradreisch** [comment]
Hi @ranger6, thanks for the fast reply.
If there are no out of the box parameters that I can use, thats ok. I need to write a little bash script to change the version parameter in a config file anyways.

Just to provide you with insights on our pipeline:
- We are using [trunk based development](https://trunkbaseddevelopment.com) with a feature branch for every user story that is merged back to master afterwards.
- The merge can have two scenarios
  1. You branched from 0.1.0... pushed several versions (e.g. 0.1.1-dev.17) and merge it back. This merge will then be bumped to 0.1.1 (after a successful test run) which is the next semantic version number. 
  2. You branched from 0.1.0... pushed several versions (e.g. 0.1.1-dev.17) and merge it back to master, where the current version is already 0.1.3. In this case you accept the incoming change from master during the merge. This merge will then be bumped to 0.1.4. 

You might end up with very high patch numbers... but that is ok for us.
The CI/CD is then running a docker build for every merge that is automatically deployed (latest) to a staging cluster.
Major and minor version changes are done manually so far. However, I want to automate this based on commit messages (e.g. [Breaking Change] in the message would automatically increase the minor version).

Anyways. Thanks for this great tool! I'll integrate it into my pipeline in the next hours.
