### ISSUE TITLE
README should factor out package manager installation notes

### ISSUE THREAD

**Issue by ranger6** [fsaintjacques/semver-tool#67]
This simple tool with no dependencies except for `bash` (not even more modern versions) is easy to install: download the single script file to anywhere, make it executable, and (if desired) be sure it is on your PATH.

However, the script has also been packaged up by (at present) two other tools: [adsf](https://asdf-vm.com/) and [bpkg](https://github.com/bpkg/bpkg).  These package managers can also install `semver` and might be useful in certain contexts, especially if the package managers are already being used.  It is doubtful that setting up a package manager just to install `semver` makes any sense.  Maybe other package managers/installers will appear: RPM, Debian, ?, .. (lol!).

The package manager details, especially how to set them up, do not belong in the `semver` README installation notes. This project does not (and should not) test the package manager setup and `semver` packaging/configuration.  Packaging is a downstream activity.

Proposed:

1.  The README file should contain pointers and a brief description of these package managers (a few lines).  It should not contain set-up procedures.
2.  These notes should not distract from the simple procedure or get in the way of the main contents of the README.  There should be pointer (link) to an "alternate installations" section to be found towards the end of the README from the "installation".

See the discussion of this in PR #65 

I think it is great that others have found the semver tool useful to the point of doing downstream packaging!  There is no reason that the `semver` project shouldn't reference these efforts.  And, we shouldn't be breaking things for these efforts (e.g. arbitrary name changes, versioning hygiene, etc).

**Comment by ranger6** [comment]
It would be good to get comments from the two contributors representing the package managers: @jwerle and @mathew-fleisch !

**Comment by mathew-fleisch** [comment]
@ranger6 maybe just make a PR? I'm not sure what exactly you're after. I like to use asdf to install tools I use in github actions that might not be installed by default and that is my main use case for this tool.

**Comment by ranger6** [comment]
> @ranger6 maybe just make a PR? I'm not sure what exactly you're after. I like to use asdf to install tools I use in github actions that might not be installed by default and that is my main use case for this tool.

Ok, here it is #68!

Just to be clear, I have nothing against package/version/dependency managers.  I've spent years working on this stuff and trying to convince others that *not* managing dependencies and *not* automating dev/build environments is a recipe for disaster.  I just want to separate the concerns of the upstream project (semver) and the downstream packaging.

**Comment by ranger6** [comment]
Resolved with PR #68

**Comment by jwerle** [comment]
yep, a simple call out with install instructions SGTM!
