### ISSUE TITLE
Is it expected, that prerel bump removes "v" prefix?

### ISSUE THREAD

**Issue by mstoetzer** [fsaintjacques/semver-tool#70]
```
semver validate v2.10.1
valid
```
```
semver bump prerel 2.10.1
2.10.1-1
```
Should the following remove "v"?
```
semver bump prerel v2.10.1
2.10.1-1
```

**Comment by ranger6** [comment]
I think the more interesting question is "Should `validate` return `valid`"?
According to the spec. and the [FAQ](https://semver.org/#is-v123-a-semantic-version), v2.10.1 (for example) is not valid (strictly speaking).  The FAQ explains that it gets used (in english), so the semver tool is permissive in what it accepts. I believe this has been in the code base for quite some time.  However, it is strict in what it emits: only valid version numbers: it strips off the ornamental "v".

**Comment by mstoetzer** [comment]
For example many docker images use "v" as prefix in their tags. I think, `semver bump prerel x.y.z` should only do, what it is meant to do. Just bump the prerelease and don't strip some prefixes.

**Comment by mstoetzer** [comment]
For example many docker images use "v" as prefix in their tags. I think, `semver bump prerel x.y.z` should only do, what it is meant to do. Just bump the prerelease and don't strip some prefixes.
